Added gcov functionality to build script.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -11,21 +11,31 @@ cat >&2 <<EOF
 Usage: $0 [-r] [-i] [-d DIR]
 	-r        do a full rebuild, removing the BDIR first
 	-i        install when done
+        -c        clean gcov files
+        -g        run gcov
 	-d DIR    set BDIR to DIR, instead of the default name derived from current git branch
 EOF
 }
 
 DO_REBUILD=0
 DO_INSTALL=0
+DO_GCOV_CLEAN=0
+DO_GCOV=0
 PRETEND=0
 
-while getopts ":ripd:" opt; do
+while getopts ":ricgpd:" opt; do
   case $opt in
     r)
 	    DO_REBUILD=1
       ;;
 	i)
 		DO_INSTALL=1
+	  ;;
+	c)
+		DO_GCOV_CLEAN=1
+	  ;;
+	g)
+		DO_GCOV=1
 	  ;;
 	p)
 		PRETEND=1
@@ -71,7 +81,7 @@ fi
 if [ ! -d "$BDIR" ]; then
 	mkdir "$BDIR"
 	cd "$BDIR"
-	../configure --prefix=$HOME/kgcc/$BRANCH --enable-languages=c++,c --disable-bootstrap --enable-maintainer-mode --disable-multilib || die "configure failed"
+	../configure --prefix=$HOME/kgcc/$BRANCH --enable-languages=c++,c --disable-bootstrap --enable-coverage --disable-multilib || die "configure failed"
 else
 	echo "Build directory already exists, skipping configure phase. Pass '-r' to do a full rebuild."
 	cd "$BDIR"
@@ -81,4 +91,16 @@ time make -j8 || die "make failed"
 
 if [ $DO_INSTALL -eq 1 ]; then
 	make install || die "make install failed"
+fi
+
+if [ $DO_GCOV_CLEAN -eq 1 ]; then
+  echo "Cleaning .gcda and .gcov files..."
+  find ./ -name "*.gcda" -exec rm {} \; 
+  find ./ -name "*.gcov" -exec rm {} \; 
+fi
+
+if [ $DO_GCOV -eq 1 ]; then
+  echo "Running gcov..."
+  cd gcc
+  gcov *.o
 fi
